### ISSUE TITLE
Incompatible with geolocator 13.0.1

### ISSUE THREAD

**Issue by mulfa8525** [daohoangson/flutter_widget_from_html#1313]
![Untitled](https://github.com/user-attachments/assets/84a75c50-3b77-4c80-b3c5-cc825b25dc9e)

Hi, sir...

Please check the latest version of geolocator (currently 13.0.1). Because the latest version of your package (0.15.1) is not compatible with geolocator 13.0.1.

Hopefully you can fix my report as soon as possible.

Thank you for your incredibly useful package.

**Comment by AtjonTV** [comment]
For anyone that needs to get it working asap and cant wait for a release.

```yaml
dependencies:
  flutter_widget_from_html: #^0.15.1 # Temporary: Using git until a release is made
    git:
      url: https://github.com/daohoangson/flutter_widget_from_html.git
      ref: 214e551f3c35c189d22546325db8b5bc103b7b88
      path: packages/enhanced
      
dependency_overrides:
  web: ^1.0.0 # Temporary: Override to web:1.0.0 until all packages are updated
  fwfh_webview: #^0.15.1 # Temporary: Using git until a release is made
    git:
      url: https://github.com/daohoangson/flutter_widget_from_html.git
      ref: 214e551f3c35c189d22546325db8b5bc103b7b88
      path: packages/fwfh_webview
```
