### ISSUE TITLE
Figcaption not follow image width

### ISSUE THREAD

**Issue by anggaaryas** [daohoangson/flutter_widget_from_html#1381]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html

<div style="text-align: left;">
            <figure><img src="https://images.unsplash.com/photo-1732919258473-2e99efcfba02?w=120&dpr=2&h=200&auto=format&fit=crop&q=60&ixid=M3wxMjA3fDB8MXxhbGx8M3x8fHx8fHx8MTczMzI4MTIxM3w&ixlib=rb-4.0.3" style="max-width:100%"></figure>
         </div>
         <div style="text-align: left;">
            <figure>Photo in the left</figure>
         </div>
         <div style="text-align: left;">
            <div style="text-align: right;">
               <figure><img src="https://images.unsplash.com/photo-1732919258473-2e99efcfba02?w=120&dpr=2&h=200&auto=format&fit=crop&q=60&ixid=M3wxMjA3fDB8MXxhbGx8M3x8fHx8fHx8MTczMzI4MTIxM3w&ixlib=rb-4.0.3" style="max-width:100%"></figure>
            </div>
            <div style="text-align: right;">
               <figure>Photo in the right<br></figure>
               <br><br>
            </div>
            <br><br>
         </div>
         <br>
         <figure>
            <img src="https://images.unsplash.com/photo-1732919258473-2e99efcfba02?w=120&dpr=2&h=200&auto=format&fit=crop&q=60&ixid=M3wxMjA3fDB8MXxhbGx8M3x8fHx8fHx8MTczMzI4MTIxM3w&ixlib=rb-4.0.3" style="max-width:100%">
            <figcaption>this is caption</figcaption>
         </figure>
         <br><br>

```
CSS:
``` css
figcaption {
                  background-color: rgba(0, 0, 0, 0.7);
                  color: #fff;
                  padding: 0.5em;
                  font-size: 12px;
                  text-align: center;
                
              }
 figure     {
                  position: relative;
                  display: inline-block;
                  margin: 0;
                }
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
HtmlWidget(
         html,
          buildAsync: true,
            customStylesBuilder: (element) {
              if (element.localName == 'figcaption') {
                return {
                  'background-color': 'rgba(0, 0, 0, 0.7)',
                  'color': '#fff',
                  'padding': '0.5em',
                  'font-size': '12px',
                  'text-align': 'center',
                };
              } else if (element.localName == 'figure') {
                return {
                  'position': 'relative',
                  'display': 'inline-block',
                  'margin': '0',
                };
              } 


              return null;
            },),
```
</details>

<details>
  <summary>Tesing environment</summary>

```
Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale en-ID)
    • Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

```
</details>

## Expected results

<img width="949" alt="Screenshot 2024-12-04 at 11 10 31" src="https://github.com/user-attachments/assets/b7c736d4-bd93-4924-854d-15b6f9becc03">

## Actual results

<img width="1202" alt="Screenshot 2024-12-04 at 11 11 11" src="https://github.com/user-attachments/assets/8a3be1c3-1b65-4c54-98bb-92148bc94a07">
