### ISSUE TITLE
Add support for svg files

### ISSUE THREAD

**Issue by rommelcarlo** [daohoangson/flutter_widget_from_html#175]
Add support for svg files. Does it have or can do with the current version

**Comment by daohoangson** [comment]
SVG support is included in the pre-release version (`0.4.0-rc.2020043001`) since #132, #133.

**Comment by imarindam** [comment]
Does it work now? 
What to do to render `.svg`? Or it is not yet released?

**Comment by daohoangson** [comment]
It works in the pre-releases (version 0.4.0-rc). The latest one is `0.4.0-rc.2020043001`.

**Comment by imarindam** [comment]
@daohoangson But I am afraid it still doesn't work for me. 
I put `.svg` in `img` tag. Can you give me a HTML where it works?

**Comment by daohoangson** [comment]
Ah, looks like only inline SVG is supported for now. I'll see whether it's possible to support network SVG.

**Comment by daohoangson** [comment]
Version `0.5.0-rc.2020071301` has been released with support for svg file over network. Please try upgrading and see whether it works for you.

**Comment by jheimesilveirazup** [comment]
I tested it with the file below and it didn't work
<img class="emoji" role="img" draggable="false" src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f6a7.svg" alt="????" width="15" />

**Comment by daohoangson** [comment]
Are you sure you are running the latest RC? It seems to work for me.

![Screen Shot 2020-07-13 at 11 41 25 PM](https://user-images.githubusercontent.com/239336/87330205-6c243300-c562-11ea-9bfe-e9723500ee06.jpg)

```dart
class Issue175 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 175')),
        body: SingleChildScrollView(
          child: HtmlWidget(kHtml),
        ),
      );
}

const kHtml = """
Hello.
<img class="emoji" role="img" draggable="false" src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f6a7.svg" alt="????" width="15" />
How are you?
""";
```

**Comment by jheimesilveirazup** [comment]
![Capturar](https://user-images.githubusercontent.com/63818444/87333168-1c6a4b00-c513-11ea-8a06-e76b2502a566.PNG)

**Comment by jheimesilveirazup** [comment]
it's changing like that

**Comment by daohoangson** [comment]
Can you copy the full error message?

Also, do you use `flutter_svg` directly in your app? If you don't, you can delete that direct dependency. v0.5.0 will use the appropriate version depending on your Flutter version.

Similarly, if you don't use `flutter_widget_from_html_core` directly, you can delete that direct dependency too.

**Comment by jheimesilveirazup** [comment]
```
name: insiders_client_flutter
description: Insiders

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_widget_from_html: 0.5.0-rc.2020071301
  url_launcher: ^5.5.0
  flutter_spinkit: ^4.1.2+1
  onesignal_flutter: ^2.5.0
  string_mask: ^0.1.0
  firebase_messaging: ^6.0.16
  mask_text_input_formatter: ^1.0.6
  device_info: ^0.4.2+4
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.1
  material_design_icons_flutter: ^4.0.5345
  shimmer: ^1.1.0
  intl: ^0.16.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.2.7+1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/img/
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    #mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_b: $runner build
    mobx_bc: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
