### ISSUE TITLE
Problem when use updated version

### ISSUE THREAD

**Issue by paulo-coutinho** [daohoangson/flutter_widget_from_html#465]
Hi,

I have the following problem:

```
So, because bibleapp depends on both flutter_widget_from_html 0.5.2+1 and video_player_platform_interface 4.0.0, version solving failed.
pub get failed (1; So, because bibleapp depends on both flutter_widget_from_html 0.5.2+1 and video_player_platform_interface 4.0.0, version solving failed.)
exit code 1
```

Pubspec:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: 2.0.0+2
  cupertino_icons: 1.0.2
  mobx: 1.2.1+4
  flutter_mobx: 1.1.0+2
  provider: 5.0.0
  path_provider: 2.0.1
  synchronized: 3.0.0
  dio: 3.0.10
  scrollable_positioned_list: 0.1.10
  simple_gesture_detector: 0.2.0
  easy_localization: 3.0.0
  flutter_widget_from_html: 0.5.2+1
  archive: 3.1.2
  uuid: 3.0.1
  video_player_platform_interface: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  mobx_codegen: 1.1.2
```

Can you help me?

Thanks.
