### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null

### ISSUE THREAD

**Issue by MindMayhem** [daohoangson/flutter_widget_from_html#769]
## Steps to Reproduce

Just update your flutter to latest 3.0.0 release

## Actual results

```
lib/src/internal/ops/anchor.dart:120:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1

    WidgetsBinding.instance?.addPostFrameCallback(
                   ^


```

**Comment by mark8044** [comment]
FYI. https://github.com/flutter/flutter/issues/103561

**Comment by daohoangson** [comment]
I'm aware of this issue. The fix is easy but this package aims to support a wide range of Flutter version so it's actually quite tricky here.

**Comment by mark8044** [comment]
> I'm aware of this issue. The fix is easy but this package aims to support a wide range of Flutter version so it's actually quite tricky here.

Do you think its a mistake by the flutter team, or this is the way going forward?  (this is going to affect many many packages)

**Comment by daohoangson** [comment]
I think changing the getter to return non-nullable type is good. That means Flutter will always provide some binding, ready to be used.

The warning is annoying but harmless. I'm sure `dart fix` can fix this automatically for apps. Packages will have to workaround if they want to support older Flutter version though.

**Comment by mark8044** [comment]
> I think changing the getter to return non-nullable type is good. That means Flutter will always provide some binding, ready to be used.
> 
> The warning is annoying but harmless. I'm sure `dart fix` can fix this automatically for apps. Packages will have to workaround if they want to support older Flutter version though.

In that case, I'm very much of the iOS mentality, out with the old and force everyone to upgrade.  Don't worry much about backward compatibility. Force the progress :)

**Comment by Hixie** [comment]
You can use something like this if you need to support multiple versions:
https://github.com/flutter/plugins/blob/4479e26172b997a4118599ca45742a7ef224e5b6/packages/camera/camera/example/lib/main.dart#L1049

**Comment by daohoangson** [comment]
Thank you for the hint Hixie. Apparently we had a similar fix 2 week ago 6d478df618de5a07e10f05000c73660645bc69ab that hasn't been released yet.

**Comment by mateusfccp** [comment]
@daohoangson Do we have any ETA for this fix to be released? This is blocking us from upgrading our project to Flutter 3.0.

**Comment by MindMayhem** [comment]
> @daohoangson Do we have any ETA for this fix to be released? This is blocking us from upgrading our project to Flutter 3.0.

it just a warning, nothing more, u can build your project anyway

**Comment by mateusfccp** [comment]
> > @daohoangson Do we have any ETA for this fix to be released? This is blocking us from upgrading our project to Flutter 3.0.
> 
> it just a warning, nothing more, u can build your project anyway

No, my project won't compile because of this.

**Comment by ncuillery** [comment]
I have upgraded to 0.8.5+3 and the red warnings are gone... 🤔 is this issue fixed?

**Comment by feinstein** [comment]
@daohoangson any updates on this?

@MindMayhem Our CI/CD is configured to block builds that generate warnings, we had to disable this only so we could compile the app using this library. This has opened a door to bugs to crawl into our app, since now we depend on manual evaluation of every warning.

**Comment by DFelten** [comment]
We're currently using my custom fork of flutter_widget_from_html from the latest version which is published on pub.dev. There I fixed the issues and make it compatible with Flutter 3.

Unfortunately you need a dependency override:

  ```yaml
dependencies:
  flutter_widget_from_html_core:
    git:
      url: https://github.com/DFelten/flutter_widget_from_html.git
      ref: tmx-flutter-3
      path: packages/enhanced/
```

```yaml
dependency_overrides:
  flutter_widget_from_html_core:
    git:
      url: https://github.com/DFelten/flutter_widget_from_html.git
      ref: tmx-flutter-3
      path: packages/core/
  font_awesome_flutter:
    path: framework/packages/font_awesome_flutter
  fwfh_webview:
    git:
      url: https://github.com/DFelten/flutter_widget_from_html.git
      ref: tmx-flutter-3
      path: packages/fwfh_webview/
```
