### ISSUE TITLE
Contents of tables are cut off

### ISSUE THREAD

**Issue by DFelten** [daohoangson/flutter_widget_from_html#852]
With the current master of the package (678aefe155d0cc078606bf5b6cbbbe8a0a9cb67b), contents in tables are being cut off.

## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<table class="table">
    <tbody>
        <tr>
            <td>Features</td>
            <td>
                <ul>
                    <p>Wischfunktion mit Nicht-Wisch-Zonen und <strong>rotierenden Wischmopps</strong></p>
                    <p>anhebbares Wischmopps&nbsp;zur Vermeidung von nassen Teppichen</p>
                </ul>
            </td>
        </tr>
    </tbody>
</table>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Testing environment</summary>

```
  flutter_widget_from_html:
    git:
      url: https://github.com/daohoangson/flutter_widget_from_html.git
      path: packages/enhanced
      ref: 678aefe155d0cc078606bf5b6cbbbe8a0a9cb67b
```

and dependency_overrides for core

```
dependency_overrides:
  flutter_widget_from_html_core:
    git:
      url: https://github.com/daohoangson/flutter_widget_from_html.git
      path: packages/core
      ref: 678aefe155d0cc078606bf5b6cbbbe8a0a9cb67b
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.74.2)
[✓] VS Code (version 1.75.0-insider)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

## Expected results

This is how it looks in the browser:

![CleanShot 2023-01-06 at 15 33 30](https://user-images.githubusercontent.com/1169185/211032930-61c11a63-1cf9-4680-b6ac-0c6a79ca87eb.png)

## Actual results

Contents in tables are being cut off within the app with the example html:

![CleanShot 2023-01-06 at 15 34 01](https://user-images.githubusercontent.com/1169185/211032996-7c83e2bc-3ab4-449d-be3c-bce800175e29.png)
